# Generated by Django 3.2.8 on 2021-12-18 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_front', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrationform',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_front.course'),
        ),
    ]
