# Generated by Django 3.2.8 on 2021-12-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Course_thumbnail',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='courses',
            name='course_short_decsrpition',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
