# Generated by Django 3.2.8 on 2022-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_front', '0005_auto_20211230_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verication',
            name='certificate_number',
            field=models.CharField(max_length=20),
        ),
    ]
